In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import matplotlib
matplotlib.rcParams["figure.figsize"] = (20, 10)

In [2]:
df=pd.read_csv("apr20_price_33_col.csv",index_col=0)

df.head()

,obj_regio1,obj_heatingType,obj_cId,obj_newlyConst,obj_pricetrend,obj_yearConstructed,obj_pricetrendbuy,obj_firingTypes,obj_ExclusiveExpose,geo_bln,...,obj_telekomInternetProductAvailable,obj_barrierFree,obj_regio3,obj_objectnumber,obj_livingSpaceRange,obj_regio2,obj_telekomTvOffer,obj_telekomUploadSpeed,obj_telekomDownloadSpeed,obj_purchasePrice
0,Sachsen,heat_pump,544685.0,y,9.12,2021.0,9.12,no_information,True,Sachsen,...,False,n,Espenhain,W16138,4.0,Leipzig_Kreis,NaN,NaN,NaN,445900.0
1,Berlin,central_heating,5240003.0,n,11.35,1934.0,11.35,gas,False,Berlin,...,True,n,Rudow_Neukölln,DHH 16042020-004,1.0,Berlin,ONE_YEAR_FREE,40 MBit/s,100 MBit/s,545000.0
2,Baden_Württemberg,stove_heating,954015.0,n,5.59,1920.0,5.59,wood,False,Baden_Württemberg,...,False,n,Heddesbach,030420201,4.0,Rhein_Neckar_Kreis,NaN,NaN,NaN,195000.0
3,Schleswig_Holstein,NaN,134629.0,n,9.62,1972.0,9.62,gas,True,Schleswig_Holstein,...,True,n,Henstedt_Ulzburg,V5062a,2.0,Segeberg_Kreis,ONE_YEAR_FREE,40 MBit/s,100 MBit/s,309000.0
4,Niedersachsen,NaN,18406763.0,n,11.40,NaN,11.40,no_information,True,Niedersachsen,...,False,n,Lähden,12385-306-17/20 EVOLUTION 136,3.0,Emsland_Kreis,NaN,NaN,NaN,267777.0

In [4]:
drop_cols = [
    "obj_cId",
    "obj_pricetrend",
    "obj_pricetrendbuy",
    "obj_ExclusiveExpose",
    "geo_bln",
    "obj_streetPlain",
    "obj_zipCode",
    "geo_land",
    "obj_immotype",
    "obj_objectnumber",
    "obj_regio2",
    "ga_cd_via"
    
    
]

df = df.drop(columns=drop_cols)

KeyError: "['obj_cId', 'obj_pricetrend', 'obj_pricetrendbuy', 'obj_ExclusiveExpose', 'geo_bln', 'obj_streetPlain', 'obj_zipCode', 'geo_land', 'obj_immotype', 'obj_objectnumber', 'obj_regio2', 'ga_cd_via'] not found in axis"

In [5]:
df.head()

,obj_regio1,obj_heatingType,obj_newlyConst,obj_yearConstructed,obj_firingTypes,obj_cellar,obj_houseNumber,obj_livingSpace,geo_krs,obj_condition,...,geo_plz,obj_noRooms,obj_telekomInternetProductAvailable,obj_barrierFree,obj_regio3,obj_livingSpaceRange,obj_telekomTvOffer,obj_telekomUploadSpeed,obj_telekomDownloadSpeed,obj_purchasePrice
0,Sachsen,heat_pump,y,2021.0,no_information,n,no_information,152.00,Leipzig_Kreis,first_time_use,...,4571.0,4.0,False,n,Espenhain,4.0,NaN,NaN,NaN,445900.0
1,Berlin,central_heating,n,1934.0,gas,y,0,65.00,Berlin,refurbished,...,12357.0,2.0,True,n,Rudow_Neukölln,1.0,ONE_YEAR_FREE,40 MBit/s,100 MBit/s,545000.0
2,Baden_Württemberg,stove_heating,n,1920.0,wood,y,no_information,159.00,Rhein_Neckar_Kreis,no_information,...,69434.0,6.5,False,n,Heddesbach,4.0,NaN,NaN,NaN,195000.0
3,Schleswig_Holstein,NaN,n,1972.0,gas,y,no_information,104.78,Segeberg_Kreis,no_information,...,24558.0,4.0,True,n,Henstedt_Ulzburg,2.0,ONE_YEAR_FREE,40 MBit/s,100 MBit/s,309000.0
4,Niedersachsen,NaN,n,NaN,no_information,n,no_information,140.00,Emsland_Kreis,no_information,...,49774.0,5.0,False,n,Lähden,3.0,NaN,NaN,NaN,267777.0

In [6]:
df.shape

(46262, 21)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 46262 entries, 0 to 46261
Data columns (total 21 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   obj_regio1                           46262 non-null  str
 1   obj_heatingType                      39004 non-null  str
 2   obj_newlyConst                       46262 non-null  str
 3   obj_yearConstructed                  40276 non-null  float64
 4   obj_firingTypes                      43063 non-null  str
 5   obj_cellar                           46262 non-null  str
 6   obj_houseNumber                      46262 non-null  str
 7   obj_livingSpace                      46262 non-null  float64
 8   geo_krs                              46262 non-null  str
 9   obj_condition                        46262 non-null  str
 10  obj_street                           46262 non-null  str
 11  geo_plz                              46262 non-null  float64
 12  obj_noRooms                          46262 non-null  float64
 13  obj_telekomInternetProductAvailable  43102 non-null  object
 14  obj_barrierFree                      46262 non-null  str
 15  obj_regio3                           46262 non-null  str
 16  obj_livingSpaceRange                 46262 non-null  float64
 17  obj_telekomTvOffer                   38326 non-null  str
 18  obj_telekomUploadSpeed               37523 non-null  str
 19  obj_telekomDownloadSpeed             37524 non-null  str
 20  obj_purchasePrice                    46262 non-null  float64
dtypes: float64(6), object(1), str(14)
memory usage: 7.4+ MB

In [8]:

df.describe()

,obj_yearConstructed,obj_livingSpace,geo_plz,obj_noRooms,obj_livingSpaceRange,obj_purchasePrice
count,40276.000000,46262.000000,46262.000000,46262.000000,46262.000000,4.626200e+04
mean,1963.727406,211.710340,47663.892223,7.088669,4.699062,5.408054e+05
std,59.398147,329.564259,26612.305104,6.248201,2.320387,1.213126e+06
min,1058.000000,0.000000,1057.000000,1.000000,1.000000,0.000000e+00
25%,1936.000000,126.000000,25560.000000,4.500000,3.000000,2.400000e+05
50%,1973.000000,160.040000,47546.000000,6.000000,4.000000,3.800000e+05
75%,2002.000000,233.000000,67823.000000,8.000000,7.000000,5.980000e+05
max,5410.000000,38500.000000,99998.000000,400.000000,8.000000,1.600000e+08

In [9]:
df.drop(columns=["Unnamed: 0"], inplace=True)

KeyError: "['Unnamed: 0'] not found in axis"

In [10]:
df.head()

,obj_regio1,obj_heatingType,obj_newlyConst,obj_yearConstructed,obj_firingTypes,obj_cellar,obj_houseNumber,obj_livingSpace,geo_krs,obj_condition,...,geo_plz,obj_noRooms,obj_telekomInternetProductAvailable,obj_barrierFree,obj_regio3,obj_livingSpaceRange,obj_telekomTvOffer,obj_telekomUploadSpeed,obj_telekomDownloadSpeed,obj_purchasePrice
0,Sachsen,heat_pump,y,2021.0,no_information,n,no_information,152.00,Leipzig_Kreis,first_time_use,...,4571.0,4.0,False,n,Espenhain,4.0,NaN,NaN,NaN,445900.0
1,Berlin,central_heating,n,1934.0,gas,y,0,65.00,Berlin,refurbished,...,12357.0,2.0,True,n,Rudow_Neukölln,1.0,ONE_YEAR_FREE,40 MBit/s,100 MBit/s,545000.0
2,Baden_Württemberg,stove_heating,n,1920.0,wood,y,no_information,159.00,Rhein_Neckar_Kreis,no_information,...,69434.0,6.5,False,n,Heddesbach,4.0,NaN,NaN,NaN,195000.0
3,Schleswig_Holstein,NaN,n,1972.0,gas,y,no_information,104.78,Segeberg_Kreis,no_information,...,24558.0,4.0,True,n,Henstedt_Ulzburg,2.0,ONE_YEAR_FREE,40 MBit/s,100 MBit/s,309000.0
4,Niedersachsen,NaN,n,NaN,no_information,n,no_information,140.00,Emsland_Kreis,no_information,...,49774.0,5.0,False,n,Lähden,3.0,NaN,NaN,NaN,267777.0

In [11]:
df.columns

Index(['obj_regio1', 'obj_heatingType', 'obj_newlyConst',
       'obj_yearConstructed', 'obj_firingTypes', 'obj_cellar',
       'obj_houseNumber', 'obj_livingSpace', 'geo_krs', 'obj_condition',
       'obj_street', 'geo_plz', 'obj_noRooms',
       'obj_telekomInternetProductAvailable', 'obj_barrierFree', 'obj_regio3',
       'obj_livingSpaceRange', 'obj_telekomTvOffer', 'obj_telekomUploadSpeed',
       'obj_telekomDownloadSpeed', 'obj_purchasePrice'],
      dtype='str')

In [12]:
df.isnull().sum()

obj_regio1                                0
obj_heatingType                        7258
obj_newlyConst                            0
obj_yearConstructed                    5986
obj_firingTypes                        3199
obj_cellar                                0
obj_houseNumber                           0
obj_livingSpace                           0
geo_krs                                   0
obj_condition                             0
obj_street                                0
geo_plz                                   0
obj_noRooms                               0
obj_telekomInternetProductAvailable    3160
obj_barrierFree                           0
obj_regio3                                0
obj_livingSpaceRange                      0
obj_telekomTvOffer                     7936
obj_telekomUploadSpeed                 8739
obj_telekomDownloadSpeed               8738
obj_purchasePrice                         0
dtype: int64

In [13]:
df.head()

,obj_regio1,obj_heatingType,obj_newlyConst,obj_yearConstructed,obj_firingTypes,obj_cellar,obj_houseNumber,obj_livingSpace,geo_krs,obj_condition,...,geo_plz,obj_noRooms,obj_telekomInternetProductAvailable,obj_barrierFree,obj_regio3,obj_livingSpaceRange,obj_telekomTvOffer,obj_telekomUploadSpeed,obj_telekomDownloadSpeed,obj_purchasePrice
0,Sachsen,heat_pump,y,2021.0,no_information,n,no_information,152.00,Leipzig_Kreis,first_time_use,...,4571.0,4.0,False,n,Espenhain,4.0,NaN,NaN,NaN,445900.0
1,Berlin,central_heating,n,1934.0,gas,y,0,65.00,Berlin,refurbished,...,12357.0,2.0,True,n,Rudow_Neukölln,1.0,ONE_YEAR_FREE,40 MBit/s,100 MBit/s,545000.0
2,Baden_Württemberg,stove_heating,n,1920.0,wood,y,no_information,159.00,Rhein_Neckar_Kreis,no_information,...,69434.0,6.5,False,n,Heddesbach,4.0,NaN,NaN,NaN,195000.0
3,Schleswig_Holstein,NaN,n,1972.0,gas,y,no_information,104.78,Segeberg_Kreis,no_information,...,24558.0,4.0,True,n,Henstedt_Ulzburg,2.0,ONE_YEAR_FREE,40 MBit/s,100 MBit/s,309000.0
4,Niedersachsen,NaN,n,NaN,no_information,n,no_information,140.00,Emsland_Kreis,no_information,...,49774.0,5.0,False,n,Lähden,3.0,NaN,NaN,NaN,267777.0

In [14]:
df.groupby("obj_regio1")["obj_regio1"].agg("count")

obj_regio1
Baden_Württemberg         5421
Bayern                    5512
Berlin                     882
Brandenburg               2164
Bremen                     329
Hamburg                    509
Hessen                    3760
Mecklenburg_Vorpommern    1667
Niedersachsen             5592
Nordrhein_Westfalen       7733
Rheinland_Pfalz           3975
Saarland                   905
Sachsen                   2481
Sachsen_Anhalt            1598
Schleswig_Holstein        2910
Thüringen                  824
Name: obj_regio1, dtype: int64

In [15]:
df = df[df['obj_regio1'] == 'Niedersachsen'].copy()
df = df.reset_index(drop=True)

In [16]:
df.head()

,obj_regio1,obj_heatingType,obj_newlyConst,obj_yearConstructed,obj_firingTypes,obj_cellar,obj_houseNumber,obj_livingSpace,geo_krs,obj_condition,...,geo_plz,obj_noRooms,obj_telekomInternetProductAvailable,obj_barrierFree,obj_regio3,obj_livingSpaceRange,obj_telekomTvOffer,obj_telekomUploadSpeed,obj_telekomDownloadSpeed,obj_purchasePrice
0,Niedersachsen,NaN,n,NaN,no_information,n,no_information,140.0,Emsland_Kreis,no_information,...,49774.0,5.0,False,n,Lähden,3.0,NaN,NaN,NaN,267777.0
1,Niedersachsen,central_heating,n,NaN,gas,n,no_information,100.0,Osterholz_Kreis,no_information,...,28865.0,3.0,True,n,Lilienthal,1.0,ONE_YEAR_FREE,"2,4 MBit/s",16 MBit/s,240000.0
2,Niedersachsen,central_heating,n,2013.0,gas,n,no_information,170.0,Verden_Kreis,well_kept,...,28832.0,6.0,True,n,Achim,5.0,ONE_YEAR_FREE,40 MBit/s,100 MBit/s,549000.0
3,Niedersachsen,central_heating,n,1909.0,oil,n,no_information,170.0,Hannover_Kreis,well_kept,...,30900.0,6.0,True,n,Wedemark,5.0,ONE_YEAR_FREE,"2,4 MBit/s",16 MBit/s,460000.0
4,Niedersachsen,NaN,n,NaN,no_information,n,no_information,140.0,Emsland_Kreis,no_information,...,49774.0,5.0,False,n,Lähden,3.0,NaN,NaN,NaN,267777.0

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5592 entries, 0 to 5591
Data columns (total 21 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   obj_regio1                           5592 non-null   str
 1   obj_heatingType                      4673 non-null   str
 2   obj_newlyConst                       5592 non-null   str
 3   obj_yearConstructed                  5055 non-null   float64
 4   obj_firingTypes                      5335 non-null   str
 5   obj_cellar                           5592 non-null   str
 6   obj_houseNumber                      5592 non-null   str
 7   obj_livingSpace                      5592 non-null   float64
 8   geo_krs                              5592 non-null   str
 9   obj_condition                        5592 non-null   str
 10  obj_street                           5592 non-null   str
 11  geo_plz                              5592 non-null   float64
 12  obj_noRooms                          5592 non-null   float64
 13  obj_telekomInternetProductAvailable  5225 non-null   object
 14  obj_barrierFree                      5592 non-null   str
 15  obj_regio3                           5592 non-null   str
 16  obj_livingSpaceRange                 5592 non-null   float64
 17  obj_telekomTvOffer                   4633 non-null   str
 18  obj_telekomUploadSpeed               4491 non-null   str
 19  obj_telekomDownloadSpeed             4491 non-null   str
 20  obj_purchasePrice                    5592 non-null   float64
dtypes: float64(6), object(1), str(14)
memory usage: 917.6+ KB

In [18]:
df.isnull().sum()

obj_regio1                                0
obj_heatingType                         919
obj_newlyConst                            0
obj_yearConstructed                     537
obj_firingTypes                         257
obj_cellar                                0
obj_houseNumber                           0
obj_livingSpace                           0
geo_krs                                   0
obj_condition                             0
obj_street                                0
geo_plz                                   0
obj_noRooms                               0
obj_telekomInternetProductAvailable     367
obj_barrierFree                           0
obj_regio3                                0
obj_livingSpaceRange                      0
obj_telekomTvOffer                      959
obj_telekomUploadSpeed                 1101
obj_telekomDownloadSpeed               1101
obj_purchasePrice                         0
dtype: int64

In [19]:
df.isnull().sum()

obj_regio1                                0
obj_heatingType                         919
obj_newlyConst                            0
obj_yearConstructed                     537
obj_firingTypes                         257
obj_cellar                                0
obj_houseNumber                           0
obj_livingSpace                           0
geo_krs                                   0
obj_condition                             0
obj_street                                0
geo_plz                                   0
obj_noRooms                               0
obj_telekomInternetProductAvailable     367
obj_barrierFree                           0
obj_regio3                                0
obj_livingSpaceRange                      0
obj_telekomTvOffer                      959
obj_telekomUploadSpeed                 1101
obj_telekomDownloadSpeed               1101
obj_purchasePrice                         0
dtype: int64

In [20]:
df['obj_heatingType'] = df['obj_heatingType'].fillna('null', inplace=True)
df['obj_firingTypes'] = df['obj_firingTypes'].fillna('null', inplace=True)
df['obj_telekomUploadSpeed'] = df['obj_telekomUploadSpeed'].fillna('null')
df['obj_telekomDownloadSpeed'] = df['obj_telekomDownloadSpeed'].fillna('null')

C:\Users\hania\AppData\Local\Temp\ipykernel_16936\221282089.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['obj_heatingType'] = df['obj_heatingType'].fillna('null', inplace=True)
C:\Users\hania\AppData\Local\Temp\ipykernel_16936\221282089.py:2: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['obj_firingTypes'] = df['obj_firingTypes'].fillna('null', inplace=True)

In [21]:
df.isnull().sum()

obj_regio1                               0
obj_heatingType                          0
obj_newlyConst                           0
obj_yearConstructed                    537
obj_firingTypes                          0
obj_cellar                               0
obj_houseNumber                          0
obj_livingSpace                          0
geo_krs                                  0
obj_condition                            0
obj_street                               0
geo_plz                                  0
obj_noRooms                              0
obj_telekomInternetProductAvailable    367
obj_barrierFree                          0
obj_regio3                               0
obj_livingSpaceRange                     0
obj_telekomTvOffer                     959
obj_telekomUploadSpeed                   0
obj_telekomDownloadSpeed                 0
obj_purchasePrice                        0
dtype: int64

In [22]:
df.drop(columns=["obj_telekomInternetProductAvailable"], inplace=True)

In [23]:
df.isnull().sum()

obj_regio1                    0
obj_heatingType               0
obj_newlyConst                0
obj_yearConstructed         537
obj_firingTypes               0
obj_cellar                    0
obj_houseNumber               0
obj_livingSpace               0
geo_krs                       0
obj_condition                 0
obj_street                    0
geo_plz                       0
obj_noRooms                   0
obj_barrierFree               0
obj_regio3                    0
obj_livingSpaceRange          0
obj_telekomTvOffer          959
obj_telekomUploadSpeed        0
obj_telekomDownloadSpeed      0
obj_purchasePrice             0
dtype: int64

In [28]:
df.to_csv("price_clean.csv", index=False)

In [24]:
df['obj_telekomTvOffer'] = df['obj_telekomTvOffer'].fillna('None')

In [25]:
df.isnull().sum()

obj_regio1                    0
obj_heatingType               0
obj_newlyConst                0
obj_yearConstructed         537
obj_firingTypes               0
obj_cellar                    0
obj_houseNumber               0
obj_livingSpace               0
geo_krs                       0
obj_condition                 0
obj_street                    0
geo_plz                       0
obj_noRooms                   0
obj_barrierFree               0
obj_regio3                    0
obj_livingSpaceRange          0
obj_telekomTvOffer            0
obj_telekomUploadSpeed        0
obj_telekomDownloadSpeed      0
obj_purchasePrice             0
dtype: int64

In [26]:
df['obj_yearConstructed'] = df['obj_yearConstructed'].fillna(df['obj_yearConstructed'].median())

In [27]:
df.isnull().sum()

obj_regio1                  0
obj_heatingType             0
obj_newlyConst              0
obj_yearConstructed         0
obj_firingTypes             0
obj_cellar                  0
obj_houseNumber             0
obj_livingSpace             0
geo_krs                     0
obj_condition               0
obj_street                  0
geo_plz                     0
obj_noRooms                 0
obj_barrierFree             0
obj_regio3                  0
obj_livingSpaceRange        0
obj_telekomTvOffer          0
obj_telekomUploadSpeed      0
obj_telekomDownloadSpeed    0
obj_purchasePrice           0
dtype: int64