In [306]:
import os 
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline
import matplotlib
from sklearn.model_selection import train_test_split
matplotlib.rcParams["figure.figsize"] = (20, 10)

In [307]:
print (os.getcwd())

c:\Users\hania\Desktop\die Weiterbildng\hoky_immobilien\hoky_immobilien\notebooks

In [308]:
df=pd.read_csv("../data/raw/apr20_price_33_col.csv",index_col=0)

In [309]:
drop_cols = [
    "obj_cId",
    "obj_pricetrend",
    "obj_pricetrendbuy",
    "obj_ExclusiveExpose",
    "geo_bln",
    "obj_streetPlain",
    "obj_zipCode",
    "geo_land",
    "obj_immotype",
    "obj_objectnumber",
    "obj_regio2",
    "ga_cd_via"
    
    
]

df = df.drop(columns=drop_cols)

In [310]:
df.head()

,obj_regio1,obj_heatingType,obj_newlyConst,obj_yearConstructed,obj_firingTypes,obj_cellar,obj_houseNumber,obj_livingSpace,geo_krs,obj_condition,...,geo_plz,obj_noRooms,obj_telekomInternetProductAvailable,obj_barrierFree,obj_regio3,obj_livingSpaceRange,obj_telekomTvOffer,obj_telekomUploadSpeed,obj_telekomDownloadSpeed,obj_purchasePrice
0,Sachsen,heat_pump,y,2021.0,no_information,n,no_information,152.00,Leipzig_Kreis,first_time_use,...,4571.0,4.0,False,n,Espenhain,4.0,NaN,NaN,NaN,445900.0
1,Berlin,central_heating,n,1934.0,gas,y,0,65.00,Berlin,refurbished,...,12357.0,2.0,True,n,Rudow_Neukölln,1.0,ONE_YEAR_FREE,40 MBit/s,100 MBit/s,545000.0
2,Baden_Württemberg,stove_heating,n,1920.0,wood,y,no_information,159.00,Rhein_Neckar_Kreis,no_information,...,69434.0,6.5,False,n,Heddesbach,4.0,NaN,NaN,NaN,195000.0
3,Schleswig_Holstein,NaN,n,1972.0,gas,y,no_information,104.78,Segeberg_Kreis,no_information,...,24558.0,4.0,True,n,Henstedt_Ulzburg,2.0,ONE_YEAR_FREE,40 MBit/s,100 MBit/s,309000.0
4,Niedersachsen,NaN,n,NaN,no_information,n,no_information,140.00,Emsland_Kreis,no_information,...,49774.0,5.0,False,n,Lähden,3.0,NaN,NaN,NaN,267777.0

In [311]:
df.shape

(46262, 21)

In [312]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 46262 entries, 0 to 46261
Data columns (total 21 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   obj_regio1                           46262 non-null  str
 1   obj_heatingType                      39004 non-null  str
 2   obj_newlyConst                       46262 non-null  str
 3   obj_yearConstructed                  40276 non-null  float64
 4   obj_firingTypes                      43063 non-null  str
 5   obj_cellar                           46262 non-null  str
 6   obj_houseNumber                      46262 non-null  str
 7   obj_livingSpace                      46262 non-null  float64
 8   geo_krs                              46262 non-null  str
 9   obj_condition                        46262 non-null  str
 10  obj_street                           46262 non-null  str
 11  geo_plz                              46262 non-null  float64
 12  obj_noRooms                          46262 non-null  float64
 13  obj_telekomInternetProductAvailable  43102 non-null  object
 14  obj_barrierFree                      46262 non-null  str
 15  obj_regio3                           46262 non-null  str
 16  obj_livingSpaceRange                 46262 non-null  float64
 17  obj_telekomTvOffer                   38326 non-null  str
 18  obj_telekomUploadSpeed               37523 non-null  str
 19  obj_telekomDownloadSpeed             37524 non-null  str
 20  obj_purchasePrice                    46262 non-null  float64
dtypes: float64(6), object(1), str(14)
memory usage: 7.4+ MB

In [313]:

df.describe()

,obj_yearConstructed,obj_livingSpace,geo_plz,obj_noRooms,obj_livingSpaceRange,obj_purchasePrice
count,40276.000000,46262.000000,46262.000000,46262.000000,46262.000000,4.626200e+04
mean,1963.727406,211.710340,47663.892223,7.088669,4.699062,5.408054e+05
std,59.398147,329.564259,26612.305104,6.248201,2.320387,1.213126e+06
min,1058.000000,0.000000,1057.000000,1.000000,1.000000,0.000000e+00
25%,1936.000000,126.000000,25560.000000,4.500000,3.000000,2.400000e+05
50%,1973.000000,160.040000,47546.000000,6.000000,4.000000,3.800000e+05
75%,2002.000000,233.000000,67823.000000,8.000000,7.000000,5.980000e+05
max,5410.000000,38500.000000,99998.000000,400.000000,8.000000,1.600000e+08

In [314]:
df.head()

,obj_regio1,obj_heatingType,obj_newlyConst,obj_yearConstructed,obj_firingTypes,obj_cellar,obj_houseNumber,obj_livingSpace,geo_krs,obj_condition,...,geo_plz,obj_noRooms,obj_telekomInternetProductAvailable,obj_barrierFree,obj_regio3,obj_livingSpaceRange,obj_telekomTvOffer,obj_telekomUploadSpeed,obj_telekomDownloadSpeed,obj_purchasePrice
0,Sachsen,heat_pump,y,2021.0,no_information,n,no_information,152.00,Leipzig_Kreis,first_time_use,...,4571.0,4.0,False,n,Espenhain,4.0,NaN,NaN,NaN,445900.0
1,Berlin,central_heating,n,1934.0,gas,y,0,65.00,Berlin,refurbished,...,12357.0,2.0,True,n,Rudow_Neukölln,1.0,ONE_YEAR_FREE,40 MBit/s,100 MBit/s,545000.0
2,Baden_Württemberg,stove_heating,n,1920.0,wood,y,no_information,159.00,Rhein_Neckar_Kreis,no_information,...,69434.0,6.5,False,n,Heddesbach,4.0,NaN,NaN,NaN,195000.0
3,Schleswig_Holstein,NaN,n,1972.0,gas,y,no_information,104.78,Segeberg_Kreis,no_information,...,24558.0,4.0,True,n,Henstedt_Ulzburg,2.0,ONE_YEAR_FREE,40 MBit/s,100 MBit/s,309000.0
4,Niedersachsen,NaN,n,NaN,no_information,n,no_information,140.00,Emsland_Kreis,no_information,...,49774.0,5.0,False,n,Lähden,3.0,NaN,NaN,NaN,267777.0

In [315]:
df.columns

Index(['obj_regio1', 'obj_heatingType', 'obj_newlyConst',
       'obj_yearConstructed', 'obj_firingTypes', 'obj_cellar',
       'obj_houseNumber', 'obj_livingSpace', 'geo_krs', 'obj_condition',
       'obj_street', 'geo_plz', 'obj_noRooms',
       'obj_telekomInternetProductAvailable', 'obj_barrierFree', 'obj_regio3',
       'obj_livingSpaceRange', 'obj_telekomTvOffer', 'obj_telekomUploadSpeed',
       'obj_telekomDownloadSpeed', 'obj_purchasePrice'],
      dtype='str')

In [316]:
df.isnull().sum()

obj_regio1                                0
obj_heatingType                        7258
obj_newlyConst                            0
obj_yearConstructed                    5986
obj_firingTypes                        3199
obj_cellar                                0
obj_houseNumber                           0
obj_livingSpace                           0
geo_krs                                   0
obj_condition                             0
obj_street                                0
geo_plz                                   0
obj_noRooms                               0
obj_telekomInternetProductAvailable    3160
obj_barrierFree                           0
obj_regio3                                0
obj_livingSpaceRange                      0
obj_telekomTvOffer                     7936
obj_telekomUploadSpeed                 8739
obj_telekomDownloadSpeed               8738
obj_purchasePrice                         0
dtype: int64

In [317]:
df.head()

,obj_regio1,obj_heatingType,obj_newlyConst,obj_yearConstructed,obj_firingTypes,obj_cellar,obj_houseNumber,obj_livingSpace,geo_krs,obj_condition,...,geo_plz,obj_noRooms,obj_telekomInternetProductAvailable,obj_barrierFree,obj_regio3,obj_livingSpaceRange,obj_telekomTvOffer,obj_telekomUploadSpeed,obj_telekomDownloadSpeed,obj_purchasePrice
0,Sachsen,heat_pump,y,2021.0,no_information,n,no_information,152.00,Leipzig_Kreis,first_time_use,...,4571.0,4.0,False,n,Espenhain,4.0,NaN,NaN,NaN,445900.0
1,Berlin,central_heating,n,1934.0,gas,y,0,65.00,Berlin,refurbished,...,12357.0,2.0,True,n,Rudow_Neukölln,1.0,ONE_YEAR_FREE,40 MBit/s,100 MBit/s,545000.0
2,Baden_Württemberg,stove_heating,n,1920.0,wood,y,no_information,159.00,Rhein_Neckar_Kreis,no_information,...,69434.0,6.5,False,n,Heddesbach,4.0,NaN,NaN,NaN,195000.0
3,Schleswig_Holstein,NaN,n,1972.0,gas,y,no_information,104.78,Segeberg_Kreis,no_information,...,24558.0,4.0,True,n,Henstedt_Ulzburg,2.0,ONE_YEAR_FREE,40 MBit/s,100 MBit/s,309000.0
4,Niedersachsen,NaN,n,NaN,no_information,n,no_information,140.00,Emsland_Kreis,no_information,...,49774.0,5.0,False,n,Lähden,3.0,NaN,NaN,NaN,267777.0

In [318]:
df.groupby("obj_regio1")["obj_regio1"].agg("count")

obj_regio1
Baden_Württemberg         5421
Bayern                    5512
Berlin                     882
Brandenburg               2164
Bremen                     329
Hamburg                    509
Hessen                    3760
Mecklenburg_Vorpommern    1667
Niedersachsen             5592
Nordrhein_Westfalen       7733
Rheinland_Pfalz           3975
Saarland                   905
Sachsen                   2481
Sachsen_Anhalt            1598
Schleswig_Holstein        2910
Thüringen                  824
Name: obj_regio1, dtype: int64

In [319]:
df = df[df['obj_regio1'] == 'Niedersachsen'].copy()
df = df.reset_index(drop=True)

In [320]:
df.head()

,obj_regio1,obj_heatingType,obj_newlyConst,obj_yearConstructed,obj_firingTypes,obj_cellar,obj_houseNumber,obj_livingSpace,geo_krs,obj_condition,...,geo_plz,obj_noRooms,obj_telekomInternetProductAvailable,obj_barrierFree,obj_regio3,obj_livingSpaceRange,obj_telekomTvOffer,obj_telekomUploadSpeed,obj_telekomDownloadSpeed,obj_purchasePrice
0,Niedersachsen,NaN,n,NaN,no_information,n,no_information,140.0,Emsland_Kreis,no_information,...,49774.0,5.0,False,n,Lähden,3.0,NaN,NaN,NaN,267777.0
1,Niedersachsen,central_heating,n,NaN,gas,n,no_information,100.0,Osterholz_Kreis,no_information,...,28865.0,3.0,True,n,Lilienthal,1.0,ONE_YEAR_FREE,"2,4 MBit/s",16 MBit/s,240000.0
2,Niedersachsen,central_heating,n,2013.0,gas,n,no_information,170.0,Verden_Kreis,well_kept,...,28832.0,6.0,True,n,Achim,5.0,ONE_YEAR_FREE,40 MBit/s,100 MBit/s,549000.0
3,Niedersachsen,central_heating,n,1909.0,oil,n,no_information,170.0,Hannover_Kreis,well_kept,...,30900.0,6.0,True,n,Wedemark,5.0,ONE_YEAR_FREE,"2,4 MBit/s",16 MBit/s,460000.0
4,Niedersachsen,NaN,n,NaN,no_information,n,no_information,140.0,Emsland_Kreis,no_information,...,49774.0,5.0,False,n,Lähden,3.0,NaN,NaN,NaN,267777.0

In [321]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5592 entries, 0 to 5591
Data columns (total 21 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   obj_regio1                           5592 non-null   str
 1   obj_heatingType                      4673 non-null   str
 2   obj_newlyConst                       5592 non-null   str
 3   obj_yearConstructed                  5055 non-null   float64
 4   obj_firingTypes                      5335 non-null   str
 5   obj_cellar                           5592 non-null   str
 6   obj_houseNumber                      5592 non-null   str
 7   obj_livingSpace                      5592 non-null   float64
 8   geo_krs                              5592 non-null   str
 9   obj_condition                        5592 non-null   str
 10  obj_street                           5592 non-null   str
 11  geo_plz                              5592 non-null   float64
 12  obj_noRooms                          5592 non-null   float64
 13  obj_telekomInternetProductAvailable  5225 non-null   object
 14  obj_barrierFree                      5592 non-null   str
 15  obj_regio3                           5592 non-null   str
 16  obj_livingSpaceRange                 5592 non-null   float64
 17  obj_telekomTvOffer                   4633 non-null   str
 18  obj_telekomUploadSpeed               4491 non-null   str
 19  obj_telekomDownloadSpeed             4491 non-null   str
 20  obj_purchasePrice                    5592 non-null   float64
dtypes: float64(6), object(1), str(14)
memory usage: 917.6+ KB

In [322]:
df.isnull().sum()

obj_regio1                                0
obj_heatingType                         919
obj_newlyConst                            0
obj_yearConstructed                     537
obj_firingTypes                         257
obj_cellar                                0
obj_houseNumber                           0
obj_livingSpace                           0
geo_krs                                   0
obj_condition                             0
obj_street                                0
geo_plz                                   0
obj_noRooms                               0
obj_telekomInternetProductAvailable     367
obj_barrierFree                           0
obj_regio3                                0
obj_livingSpaceRange                      0
obj_telekomTvOffer                      959
obj_telekomUploadSpeed                 1101
obj_telekomDownloadSpeed               1101
obj_purchasePrice                         0
dtype: int64

In [323]:
df.isnull().sum()

obj_regio1                                0
obj_heatingType                         919
obj_newlyConst                            0
obj_yearConstructed                     537
obj_firingTypes                         257
obj_cellar                                0
obj_houseNumber                           0
obj_livingSpace                           0
geo_krs                                   0
obj_condition                             0
obj_street                                0
geo_plz                                   0
obj_noRooms                               0
obj_telekomInternetProductAvailable     367
obj_barrierFree                           0
obj_regio3                                0
obj_livingSpaceRange                      0
obj_telekomTvOffer                      959
obj_telekomUploadSpeed                 1101
obj_telekomDownloadSpeed               1101
obj_purchasePrice                         0
dtype: int64

In [324]:
df = df.drop(columns=["obj_telekomTvOffer", "obj_heatingType"])

In [325]:

df = df.replace('no_information', None)

In [326]:
# 5. تنظيف وتحويل سرعات الإنترنت إلى Float (مع مراعاة الفواصل والنصوص مثل MBit/s)
# الكود أدناه بيحذف أي نصوص وفراغات، وبيستبدل الفاصلة بمشغل النقطة عشان البايثون يفهمها كأرقام عشريّة
for col in ['obj_telekomUploadSpeed', 'obj_telekomDownloadSpeed']:
    df[col] = df[col].astype(str).str.replace(' MBit/s', '', case=False, regex=False)
    df[col] = df[col].str.replace(',', '.', regex=False).str.strip()
    df[col] = pd.to_numeric(df[col], errors='coerce') # 'coerce' بتحول أي قيمة نصية غريبة إلى NaN عشان ما يضرب الكود

In [327]:
df = df.dropna(subset=['obj_yearConstructed'])

In [328]:
df.isnull().sum()

obj_regio1                                0
obj_newlyConst                            0
obj_yearConstructed                       0
obj_firingTypes                         799
obj_cellar                                0
obj_houseNumber                        4583
obj_livingSpace                           0
geo_krs                                   0
obj_condition                          1558
obj_street                             4583
geo_plz                                   0
obj_noRooms                               0
obj_telekomInternetProductAvailable     326
obj_barrierFree                           0
obj_regio3                                0
obj_livingSpaceRange                      0
obj_telekomUploadSpeed                  983
obj_telekomDownloadSpeed                983
obj_purchasePrice                         0
dtype: int64

In [329]:
df.head(3)

,obj_regio1,obj_newlyConst,obj_yearConstructed,obj_firingTypes,obj_cellar,obj_houseNumber,obj_livingSpace,geo_krs,obj_condition,obj_street,geo_plz,obj_noRooms,obj_telekomInternetProductAvailable,obj_barrierFree,obj_regio3,obj_livingSpaceRange,obj_telekomUploadSpeed,obj_telekomDownloadSpeed,obj_purchasePrice
2,Niedersachsen,n,2013.0,gas,n,NaN,170.0,Verden_Kreis,well_kept,NaN,28832.0,6.0,True,n,Achim,5.0,40.0,100.0,549000.0
3,Niedersachsen,n,1909.0,oil,n,NaN,170.0,Hannover_Kreis,well_kept,NaN,30900.0,6.0,True,n,Wedemark,5.0,2.4,16.0,460000.0
5,Niedersachsen,n,1969.0,district_heating,y,NaN,116.0,Celle_Kreis,well_kept,NaN,29353.0,6.0,True,n,Ahnsbeck,2.0,10.0,50.0,148500.0

In [330]:
df['obj_purchasePrice_per_qm']=df['obj_purchasePrice']/df['obj_livingSpace']

In [331]:
df.to_csv("../data/price_clean.csv")

In [332]:
df.head(3)

,obj_regio1,obj_newlyConst,obj_yearConstructed,obj_firingTypes,obj_cellar,obj_houseNumber,obj_livingSpace,geo_krs,obj_condition,obj_street,geo_plz,obj_noRooms,obj_telekomInternetProductAvailable,obj_barrierFree,obj_regio3,obj_livingSpaceRange,obj_telekomUploadSpeed,obj_telekomDownloadSpeed,obj_purchasePrice,obj_purchasePrice_per_qm
2,Niedersachsen,n,2013.0,gas,n,NaN,170.0,Verden_Kreis,well_kept,NaN,28832.0,6.0,True,n,Achim,5.0,40.0,100.0,549000.0,3229.411765
3,Niedersachsen,n,1909.0,oil,n,NaN,170.0,Hannover_Kreis,well_kept,NaN,30900.0,6.0,True,n,Wedemark,5.0,2.4,16.0,460000.0,2705.882353
5,Niedersachsen,n,1969.0,district_heating,y,NaN,116.0,Celle_Kreis,well_kept,NaN,29353.0,6.0,True,n,Ahnsbeck,2.0,10.0,50.0,148500.0,1280.172414

In [333]:
len(df.obj_regio3.unique())

908

In [334]:
df.obj_regio3=df.obj_regio3.apply(lambda x: x.strip())
riegonal=df.obj_regio3.groupby(df.obj_regio3).agg("count").sort_values(ascending=False)
riegonal

obj_regio3
Aurich          73
Hameln          63
Norden          57
Cuxhaven        56
Celle           43
                ..
Remlingen        1
Reinstorf        1
Ahlden_Aller     1
Wüste            1
Wülferode        1
Name: obj_regio3, Length: 908, dtype: int64

In [335]:
len(riegonal[riegonal < 10])

757

In [336]:
df.obj_regio3=df.obj_regio3.apply(lambda x: 'other' if x in riegonal[riegonal <10] else x)
len(df.obj_regio3.unique())

152

In [337]:
df.head()

,obj_regio1,obj_newlyConst,obj_yearConstructed,obj_firingTypes,obj_cellar,obj_houseNumber,obj_livingSpace,geo_krs,obj_condition,obj_street,geo_plz,obj_noRooms,obj_telekomInternetProductAvailable,obj_barrierFree,obj_regio3,obj_livingSpaceRange,obj_telekomUploadSpeed,obj_telekomDownloadSpeed,obj_purchasePrice,obj_purchasePrice_per_qm
2,Niedersachsen,n,2013.0,gas,n,NaN,170.0,Verden_Kreis,well_kept,NaN,28832.0,6.0,True,n,Achim,5.0,40.0,100.0,549000.0,3229.411765
3,Niedersachsen,n,1909.0,oil,n,NaN,170.0,Hannover_Kreis,well_kept,NaN,30900.0,6.0,True,n,Wedemark,5.0,2.4,16.0,460000.0,2705.882353
5,Niedersachsen,n,1969.0,district_heating,y,NaN,116.0,Celle_Kreis,well_kept,NaN,29353.0,6.0,True,n,other,2.0,10.0,50.0,148500.0,1280.172414
6,Niedersachsen,y,2020.0,NaN,n,NaN,133.0,Helmstedt_Kreis,first_time_use,NaN,38364.0,4.0,True,n,Schöningen,3.0,40.0,100.0,248400.0,1867.669173
10,Niedersachsen,n,2000.0,district_heating,y,NaN,136.0,Wolfsburg,well_kept,NaN,38446.0,5.0,True,y,other,3.0,2.4,16.0,369000.0,2713.235294

In [338]:
df.isnull().sum()

obj_regio1                                0
obj_newlyConst                            0
obj_yearConstructed                       0
obj_firingTypes                         799
obj_cellar                                0
obj_houseNumber                        4583
obj_livingSpace                           0
geo_krs                                   0
obj_condition                          1558
obj_street                             4583
geo_plz                                   0
obj_noRooms                               0
obj_telekomInternetProductAvailable     326
obj_barrierFree                           0
obj_regio3                                0
obj_livingSpaceRange                      0
obj_telekomUploadSpeed                  983
obj_telekomDownloadSpeed                983
obj_purchasePrice                         0
obj_purchasePrice_per_qm                  0
dtype: int64

In [339]:
df.to_csv("../data/price_clean.csv", index=False)

In [340]:
df[df.obj_livingSpace/df.obj_noRooms <= 100].head()

,obj_regio1,obj_newlyConst,obj_yearConstructed,obj_firingTypes,obj_cellar,obj_houseNumber,obj_livingSpace,geo_krs,obj_condition,obj_street,geo_plz,obj_noRooms,obj_telekomInternetProductAvailable,obj_barrierFree,obj_regio3,obj_livingSpaceRange,obj_telekomUploadSpeed,obj_telekomDownloadSpeed,obj_purchasePrice,obj_purchasePrice_per_qm
2,Niedersachsen,n,2013.0,gas,n,NaN,170.0,Verden_Kreis,well_kept,NaN,28832.0,6.0,True,n,Achim,5.0,40.0,100.0,549000.0,3229.411765
3,Niedersachsen,n,1909.0,oil,n,NaN,170.0,Hannover_Kreis,well_kept,NaN,30900.0,6.0,True,n,Wedemark,5.0,2.4,16.0,460000.0,2705.882353
5,Niedersachsen,n,1969.0,district_heating,y,NaN,116.0,Celle_Kreis,well_kept,NaN,29353.0,6.0,True,n,other,2.0,10.0,50.0,148500.0,1280.172414
6,Niedersachsen,y,2020.0,NaN,n,NaN,133.0,Helmstedt_Kreis,first_time_use,NaN,38364.0,4.0,True,n,Schöningen,3.0,40.0,100.0,248400.0,1867.669173
10,Niedersachsen,n,2000.0,district_heating,y,NaN,136.0,Wolfsburg,well_kept,NaN,38446.0,5.0,True,y,other,3.0,2.4,16.0,369000.0,2713.235294

In [341]:
df['obj_livingSpace'].unique()

array([170.  , 116.  , 133.  , ..., 158.7 , 104.87, 102.35], shape=(1160,))

In [342]:
df.shape

(5055, 20)

In [343]:
df[~(df.obj_livingSpace/df.obj_noRooms<300)]
df.shape

(5055, 20)

In [344]:
df['obj_purchasePrice_per_qm'].describe()

c:\Users\hania\Desktop\die Weiterbildng\hoky_immobilien\.venv\Lib\site-packages\pandas\core\nanops.py:1028: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

count    5055.000000
mean             inf
std              NaN
min         0.000000
25%      1280.562397
50%      1888.888889
75%      2572.344744
max              inf
Name: obj_purchasePrice_per_qm, dtype: float64

In [345]:
# 1. استبعاد الصفوف التي تكون فيها المساحة أو السعر صفر أو أقل
df = df[df['obj_livingSpace'] > 0]
df = df[df['obj_purchasePrice'] > 0]

# 2. إعادة حساب سعر المتر المربع بعد التنظيف
df['obj_purchasePrice_per_qm'] = df['obj_purchasePrice'] / df['obj_livingSpace']

# 3. عرض الوصف الإحصائي للعمود الآن
df['obj_purchasePrice_per_qm'].describe()

count     5040.000000
mean      2009.805239
std       1122.482862
min          0.006250
25%       1283.555400
50%       1890.301358
75%       2571.598639
max      27267.706751
Name: obj_purchasePrice_per_qm, dtype: float64

In [346]:
df.shape

(5040, 20)